#!/usr/bin/env bash
# deploy.sh — First-time setup and launch for mcp-consulting-kit showcase servers
#
# Usage:
#   ./scripts/deploy.sh           # setup + start all three showcase servers
#   ./scripts/deploy.sh --docker  # build & start via Docker Compose instead
#   ./scripts/deploy.sh --check   # prerequisite check only (no launch)
#
# After the first run, use ./launch.sh to start/stop servers without reinstalling.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHOWCASE="$REPO_ROOT/showcase-servers"
LOG_DIR="$REPO_ROOT/logs"

# ─── helpers ──────────────────────────────────────────────────────────────────
green()  { echo -e "\033[0;32m$*\033[0m"; }
yellow() { echo -e "\033[0;33m$*\033[0m"; }
red()    { echo -e "\033[0;31m$*\033[0m"; }
die()    { red "ERROR: $*"; exit 1; }

# ─── argument parsing ─────────────────────────────────────────────────────────
USE_DOCKER=false
CHECK_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --docker) USE_DOCKER=true ;;
    --check)  CHECK_ONLY=true ;;
    --help|-h)
      echo "Usage: $0 [--docker] [--check]"
      echo "  (no flags)  Install Python deps and start servers locally"
      echo "  --docker    Build and start via Docker Compose"
      echo "  --check     Check prerequisites only, do not start servers"
      exit 0
      ;;
    *) die "Unknown argument: $arg" ;;
  esac
done

# ─── 1. prerequisite checks ───────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════"
echo " mcp-consulting-kit  —  Deploy / Quick-start"
echo "══════════════════════════════════════════════════════"
echo ""
echo "▶ Checking prerequisites..."

ERRORS=0

# Python 3.11+
PYTHON=$(command -v python3 2>/dev/null || command -v python 2>/dev/null || echo "")
if [ -z "$PYTHON" ]; then
  red "  ✗ Python 3.11+ not found.  Install from https://python.org/downloads/"
  ERRORS=$((ERRORS+1))
else
  PY_VER=$("$PYTHON" -c "import sys; print('%d.%d' % sys.version_info[:2])")
  PY_MIN=$("$PYTHON" -c "import sys; print(1 if sys.version_info >= (3,11) else 0)")
  if [ "$PY_MIN" = "1" ]; then
    green "  ✓ Python $PY_VER ($PYTHON)"
  else
    red "  ✗ Python $PY_VER detected — 3.11 or newer is required."
    ERRORS=$((ERRORS+1))
  fi
fi

# pip
if "$PYTHON" -m pip --version > /dev/null 2>&1; then
  green "  ✓ pip available"
else
  red "  ✗ pip not available.  Run: $PYTHON -m ensurepip --upgrade"
  ERRORS=$((ERRORS+1))
fi

# curl (for health checks)
if command -v curl > /dev/null 2>&1; then
  green "  ✓ curl available"
else
  yellow "  ⚠ curl not found — health checks will be skipped"
fi

# Docker (only required with --docker flag)
if $USE_DOCKER; then
  if command -v docker > /dev/null 2>&1; then
    green "  ✓ Docker $(docker --version | awk '{print $3}' | tr -d ',')"
  else
    red "  ✗ Docker not found.  Install from https://docs.docker.com/get-docker/"
    ERRORS=$((ERRORS+1))
  fi
  if command -v docker-compose > /dev/null 2>&1 || docker compose version > /dev/null 2>&1; then
    green "  ✓ Docker Compose available"
  else
    red "  ✗ Docker Compose not found.  Install from https://docs.docker.com/compose/"
    ERRORS=$((ERRORS+1))
  fi
fi

if [ "$ERRORS" -gt 0 ]; then
  echo ""
  die "$ERRORS prerequisite(s) missing.  Fix them and re-run this script."
fi

echo ""
green "All prerequisites satisfied."

if $CHECK_ONLY; then
  exit 0
fi

# ─── 2. generate .env files ───────────────────────────────────────────────────
echo ""
echo "▶ Setting up .env files..."

SERVERS=(business-intelligence-mcp api-integration-hub content-automation-mcp)
PORTS=(8101 8102 8103)

# Generate a random API key (urandom → hex, fallback to timestamp-based)
rand_key() {
  if command -v openssl > /dev/null 2>&1; then
    openssl rand -hex 32
  else
    "$PYTHON" -c "import secrets; print(secrets.token_hex(32))"
  fi
}

API_KEY=$(rand_key)

for i in "${!SERVERS[@]}"; do
  SRV="${SERVERS[$i]}"
  PORT="${PORTS[$i]}"
  ENV_FILE="$SHOWCASE/$SRV/.env"

  if [ -f "$ENV_FILE" ]; then
    yellow "  ⚠ $SRV/.env already exists — skipping (delete it to regenerate)"
  else
    cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Replace placeholder values with real credentials for your environment.

# API authentication — shared key for all showcase servers
API_KEYS=${API_KEY}

PORT=${PORT}

# Uncomment and fill in if using a real database (BI server only)
# DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# Uncomment to enable LLM-powered natural language queries (BI server only)
# LLM_PROVIDER=claude
# ANTHROPIC_API_KEY=sk-ant-...

# Uncomment for Slack / GitHub / Stripe integration (API Hub only)
# SLACK_BOT_TOKEN=xoxb-...
# GITHUB_TOKEN=ghp_...
# STRIPE_SECRET_KEY=sk_...

# Redis for rate limiting (optional — in-memory fallback used if absent)
# REDIS_URL=redis://localhost:6379
EOF
    green "  ✓ Created $SRV/.env  (API_KEYS auto-generated)"
  fi
done

echo ""
yellow "  API key written to .env files: ${API_KEY:0:8}…"
yellow "  Keep this value — you will need it to authenticate API requests."

# ─── 3a. Docker Compose path ──────────────────────────────────────────────────
if $USE_DOCKER; then
  echo ""
  echo "▶ Building and starting containers (this takes 2–4 minutes on first run)..."
  cd "$REPO_ROOT"

  COMPOSE_CMD="docker compose"
  command -v docker-compose > /dev/null 2>&1 && COMPOSE_CMD="docker-compose"

  $COMPOSE_CMD up --build -d business-intelligence-mcp api-integration-hub content-automation-mcp

  echo ""
  echo "▶ Waiting for containers to start (15 s)..."
  sleep 15

  health_check_docker() {
    local name="$1"; local port="$2"
    if ! command -v curl > /dev/null 2>&1; then
      yellow "  ! $name → skipping http://localhost:$port/health check (curl not installed)"
      return 0
    fi
    if curl -sf --max-time 5 "http://localhost:$port/health" > /dev/null 2>&1; then
      green "  ✓ $name → http://localhost:$port/health"
    else
      red "  ✗ $name → http://localhost:$port/health — not responding"
      DOCKER_HEALTHY=false
    fi
  }

  DOCKER_HEALTHY=true
  echo ""
  echo "▶ Verifying server health..."
  for i in "${!SERVERS[@]}"; do
    health_check_docker "${SERVERS[$i]}" "${PORTS[$i]}"
  done

  if $DOCKER_HEALTHY; then
    echo ""
    green "════════════════════════════════════════════════"
    green " Deploy complete (Docker mode)"
    green "  BI MCP        → http://localhost:8101/health"
    green "  API Hub       → http://localhost:8102/health"
    green "  Content MCP   → http://localhost:8103/health"
    green ""
    green "  Authenticate: X-API-Key: $API_KEY"
    green "  Stop:  docker compose down"
    green "  Logs:  docker compose logs -f"
    green "════════════════════════════════════════════════"
    exit 0
  else
    yellow "════════════════════════════════════════════════"
    yellow " Deploy finished with warnings — see above"
    yellow "  Logs:  docker compose logs -f"
    yellow " Troubleshooting guide: docs/QUICKSTART-DEPLOY.md"
    yellow "════════════════════════════════════════════════"
    exit 1
  fi
fi

# ─── 3b. Local (uvicorn) path ─────────────────────────────────────────────────
echo ""
echo "▶ Installing Python dependencies..."

for SRV in "${SERVERS[@]}"; do
  REQ="$SHOWCASE/$SRV/requirements.txt"
  if [ -f "$REQ" ]; then
    echo "  Installing $SRV..."
    "$PYTHON" -m pip install --quiet -r "$REQ"
    green "  ✓ $SRV dependencies installed"
  else
    yellow "  ⚠ No requirements.txt found for $SRV"
  fi
done

# ─── 4. launch servers ────────────────────────────────────────────────────────
echo ""
echo "▶ Starting servers..."
mkdir -p "$LOG_DIR"
PID_FILE="$REPO_ROOT/.server-pids"
> "$PID_FILE"

for i in "${!SERVERS[@]}"; do
  SRV="${SERVERS[$i]}"
  PORT="${PORTS[$i]}"
  DIR="$SHOWCASE/$SRV"
  LOG="$LOG_DIR/$SRV.log"

  # Load .env
  if [ -f "$DIR/.env" ]; then
    set -a; source "$DIR/.env"; set +a
  fi

  cd "$DIR"
  "$PYTHON" -m uvicorn main:app --host 0.0.0.0 --port "$PORT" > "$LOG" 2>&1 &
  PID=$!
  echo "$PID" >> "$PID_FILE"
  green "  ✓ $SRV → http://localhost:$PORT  (pid $PID)"
  cd "$REPO_ROOT"
  sleep 0.3
done

# ─── 5. health checks ─────────────────────────────────────────────────────────
echo ""
echo "▶ Waiting for servers to start (10 s)..."
sleep 10

echo ""
echo "▶ Verifying server health..."
ALL_HEALTHY=true
if command -v curl > /dev/null 2>&1; then
  for i in "${!SERVERS[@]}"; do
    SRV="${SERVERS[$i]}"
    PORT="${PORTS[$i]}"
    if curl -sf --max-time 5 "http://localhost:$PORT/health" > /dev/null 2>&1; then
      green "  ✓ $SRV → http://localhost:$PORT/health"
    else
      red "  ✗ $SRV → http://localhost:$PORT/health — not responding"
      yellow "    Check logs: cat $LOG_DIR/$SRV.log"
      ALL_HEALTHY=false
    fi
  done
else
  yellow "  ! curl not found; skipping local health checks"
  yellow "    Install curl to enable automatic /health verification"
fi

echo ""
if $ALL_HEALTHY; then
  green "════════════════════════════════════════════════"
  green " Deploy complete ✓"
  green ""
  green "  BI MCP        → http://localhost:8101/health"
  green "  API Hub       → http://localhost:8102/health"
  green "  Content MCP   → http://localhost:8103/health"
  green ""
  green "  Authenticate: X-API-Key: $API_KEY"
  green ""
  green "  Stop:    ./launch.sh stop"
  green "  Logs:    ./launch.sh logs"
  green "  Restart: ./launch.sh restart"
  green "════════════════════════════════════════════════"
else
  yellow "════════════════════════════════════════════════"
  yellow " Deploy finished with warnings — see above"
  yellow " Troubleshooting guide: docs/QUICKSTART-DEPLOY.md"
  yellow "════════════════════════════════════════════════"
  exit 1
fi
