# deploy.ps1 — First-time setup and launch for mcp-consulting-kit showcase servers
#
# Usage:
#   .\scripts\deploy.ps1             # setup + start all three showcase servers locally
#   .\scripts\deploy.ps1 -Docker     # build & start via Docker Compose instead
#   .\scripts\deploy.ps1 -CheckOnly  # prerequisite check only, no launch
#
# After the first run, use .\launch-servers.ps1 to start servers without reinstalling.

[CmdletBinding()]
param(
    [switch]$Docker,
    [switch]$CheckOnly
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent $PSScriptRoot
$ShowcaseRoot = Join-Path $RepoRoot "showcase-servers"
$LogDir = Join-Path $RepoRoot "logs"

$Servers = @(
    @{ Name = "business-intelligence-mcp"; Port = 8101 },
    @{ Name = "api-integration-hub";        Port = 8102 },
    @{ Name = "content-automation-mcp";     Port = 8103 }
)

# ─── helpers ──────────────────────────────────────────────────────────────────
function Write-Green  { param($Msg) Write-Host $Msg -ForegroundColor Green  }
function Write-Yellow { param($Msg) Write-Host $Msg -ForegroundColor Yellow }
function Write-Red    { param($Msg) Write-Host $Msg -ForegroundColor Red    }
function Fail         { param($Msg) Write-Red "ERROR: $Msg"; exit 1          }

# ─── 1. prerequisite checks ───────────────────────────────────────────────────
Write-Host ""
Write-Host "══════════════════════════════════════════════════════"
Write-Host " mcp-consulting-kit  —  Deploy / Quick-start"
Write-Host "══════════════════════════════════════════════════════"
Write-Host ""
Write-Host "▶ Checking prerequisites..."

$Errors = 0

# Python 3.11+
$PythonCmd = $null
foreach ($candidate in @("python", "python3", "py")) {
    try {
        $ver = & $candidate --version 2>&1
        if ($ver -match "Python (\d+)\.(\d+)") {
            $major = [int]$Matches[1]; $minor = [int]$Matches[2]
            if ($major -gt 3 -or ($major -eq 3 -and $minor -ge 11)) {
                Write-Green "  ✓ Python $major.$minor ($candidate)"
                $PythonCmd = $candidate
                break
            } else {
                Write-Red "  ✗ Python $major.$minor detected — 3.11 or newer is required."
                $Errors++
                break
            }
        }
    } catch { }
}
if (-not $PythonCmd -and $Errors -eq 0) {
    Write-Red "  ✗ Python 3.11+ not found.  Install from https://python.org/downloads/"
    $Errors++
}

# pip
if ($PythonCmd) {
    try {
        & $PythonCmd -m pip --version | Out-Null
        Write-Green "  ✓ pip available"
    } catch {
        Write-Red "  ✗ pip not available.  Run: $PythonCmd -m ensurepip --upgrade"
        $Errors++
    }
}

# curl for health checks (built into Windows 10+)
if (Get-Command curl.exe -ErrorAction SilentlyContinue) {
    Write-Green "  ✓ curl available"
} else {
    Write-Yellow "  ⚠ curl.exe not found — health checks will be skipped"
}

if ($Docker) {
    # Docker
    try {
        $dv = docker --version 2>&1
        Write-Green "  ✓ $dv"
    } catch {
        Write-Red "  ✗ Docker not found.  Install from https://docs.docker.com/get-docker/"
        $Errors++
    }
    # Docker Compose
    try {
        docker compose version | Out-Null
        Write-Green "  ✓ Docker Compose available"
    } catch {
        try {
            docker-compose version | Out-Null
            Write-Green "  ✓ docker-compose available"
        } catch {
            Write-Red "  ✗ Docker Compose not found.  Install from https://docs.docker.com/compose/"
            $Errors++
        }
    }
}

if ($Errors -gt 0) {
    Write-Host ""
    Fail "$Errors prerequisite(s) missing.  Fix them and re-run this script."
}

Write-Host ""
Write-Green "All prerequisites satisfied."

if ($CheckOnly) { exit 0 }

# ─── 2. generate .env files ───────────────────────────────────────────────────
Write-Host ""
Write-Host "▶ Setting up .env files..."

# Generate a random 32-byte hex API key
$ApiKey = -join ((1..32) | ForEach-Object { '{0:x2}' -f (Get-Random -Maximum 256) })

foreach ($srv in $Servers) {
    $name = $srv.Name
    $port = $srv.Port
    $envPath = Join-Path $ShowcaseRoot "$name\.env"

    if (Test-Path $envPath) {
        Write-Yellow "  ⚠ $name\.env already exists — skipping (delete to regenerate)"
    } else {
        $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
        $content = @"
# Auto-generated by deploy.ps1 — $timestamp
# Replace placeholder values with real credentials for your environment.

# API authentication — shared key for all showcase servers
API_KEYS=$ApiKey

PORT=$port

# Uncomment and fill in if using a real database (BI server only)
# DATABASE_URL=postgresql://user:password@localhost:5432/mydb

# Uncomment to enable LLM-powered natural language queries (BI server only)
# LLM_PROVIDER=claude
# ANTHROPIC_API_KEY=sk-ant-...

# Uncomment for Slack / GitHub / Stripe integration (API Hub only)
# SLACK_BOT_TOKEN=xoxb-...
# GITHUB_TOKEN=ghp_...
# STRIPE_SECRET_KEY=sk_...

# Redis for rate limiting (optional — in-memory fallback used if absent)
# REDIS_URL=redis://localhost:6379
"@
        Set-Content -Path $envPath -Value $content -Encoding UTF8
        Write-Green "  ✓ Created $name\.env  (API_KEYS auto-generated)"
    }
}

Write-Host ""
$preview = $ApiKey.Substring(0, 8)
Write-Yellow "  API key written to .env files: ${preview}…"
Write-Yellow "  Keep this value — you will need it to authenticate API requests."

# ─── 3a. Docker Compose path ──────────────────────────────────────────────────
if ($Docker) {
    Write-Host ""
    Write-Host "▶ Building and starting containers (this takes 2–4 minutes on first run)..."
    Set-Location $RepoRoot

    $composeArgs = @("up", "--build", "-d",
        "business-intelligence-mcp", "api-integration-hub", "content-automation-mcp")
    try {
        docker compose @composeArgs
    } catch {
        docker-compose @composeArgs
    }

    Write-Host ""
    Write-Host "▶ Waiting for containers to start (15 s)..."
    Start-Sleep -Seconds 15

    Write-Host ""
    Write-Host "▶ Verifying server health..."
    $DockerHealthy = $true
    foreach ($srv in $Servers) {
        $url = "http://localhost:$($srv.Port)/health"
        try {
            $resp = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
            if ($resp.StatusCode -eq 200) {
                Write-Green "  ✓ $($srv.Name) → $url"
            } else {
                Write-Red "  ✗ $($srv.Name) → $url  (HTTP $($resp.StatusCode))"
                $DockerHealthy = $false
            }
        } catch {
            Write-Red "  ✗ $($srv.Name) → $url  — not responding"
            Write-Yellow "    Logs:  docker compose logs $($srv.Name)"
            $DockerHealthy = $false
        }
    }

    Write-Host ""
    if ($DockerHealthy) {
        Write-Green "════════════════════════════════════════════════"
        Write-Green " Deploy complete (Docker mode)"
        Write-Green "  BI MCP        → http://localhost:8101/health"
        Write-Green "  API Hub       → http://localhost:8102/health"
        Write-Green "  Content MCP   → http://localhost:8103/health"
        Write-Green ""
        Write-Green "  Authenticate: X-API-Key: $ApiKey"
        Write-Green "  Stop:  docker compose down"
        Write-Green "  Logs:  docker compose logs -f"
        Write-Green "════════════════════════════════════════════════"
        exit 0
    } else {
        Write-Yellow "════════════════════════════════════════════════"
        Write-Yellow " Deploy finished with warnings — see above"
        Write-Yellow "  Logs:  docker compose logs -f"
        Write-Yellow " Troubleshooting guide: docs\QUICKSTART-DEPLOY.md"
        Write-Yellow "════════════════════════════════════════════════"
        exit 1
    }
}

# ─── 3b. Local (uvicorn) path ─────────────────────────────────────────────────
Write-Host ""
Write-Host "▶ Installing Python dependencies..."

foreach ($srv in $Servers) {
    $reqPath = Join-Path $ShowcaseRoot "$($srv.Name)\requirements.txt"
    if (Test-Path $reqPath) {
        Write-Host "  Installing $($srv.Name)..."
        & $PythonCmd -m pip install --quiet -r $reqPath
        Write-Green "  ✓ $($srv.Name) dependencies installed"
    } else {
        Write-Yellow "  ⚠ No requirements.txt found for $($srv.Name)"
    }
}

# ─── 4. launch servers ────────────────────────────────────────────────────────
Write-Host ""
Write-Host "▶ Starting servers..."
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir | Out-Null }

foreach ($srv in $Servers) {
    $name = $srv.Name
    $port = $srv.Port
    $dir  = Join-Path $ShowcaseRoot $name
    $log  = Join-Path $LogDir "$name.log"

    $cmd = @"
`$ErrorActionPreference = 'SilentlyContinue'
Set-Location '$dir'
if (Test-Path .env) {
    Get-Content .env | ForEach-Object {
        if (`$_ -match '^\s*#' -or `$_ -notmatch '=') { return }
        `$p = `$_ -split '=', 2
        [System.Environment]::SetEnvironmentVariable(`$p[0].Trim(), `$p[1].Trim())
    }
}
& $PythonCmd -m uvicorn main:app --host 0.0.0.0 --port $port 2>&1 | Tee-Object -FilePath '$log'
"@
    Start-Process powershell -ArgumentList "-NoExit", "-Command", $cmd -WindowStyle Minimized
    Write-Green "  ✓ $name → http://localhost:$port"
    Start-Sleep -Milliseconds 400
}

# ─── 5. health checks ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "▶ Waiting for servers to start (10 s)..."
Start-Sleep -Seconds 10

Write-Host ""
Write-Host "▶ Verifying server health..."
$AllHealthy = $true
foreach ($srv in $Servers) {
    $url = "http://localhost:$($srv.Port)/health"
    try {
        $resp = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 5 -ErrorAction Stop
        if ($resp.StatusCode -eq 200) {
            Write-Green "  ✓ $($srv.Name) → $url"
        } else {
            Write-Red "  ✗ $($srv.Name) → $url  (HTTP $($resp.StatusCode))"
            $AllHealthy = $false
        }
    } catch {
        Write-Red "  ✗ $($srv.Name) → $url  — not responding"
        Write-Yellow "    Check logs: Get-Content '$LogDir\$($srv.Name).log'"
        $AllHealthy = $false
    }
}

Write-Host ""
if ($AllHealthy) {
    Write-Green "════════════════════════════════════════════════"
    Write-Green " Deploy complete ✓"
    Write-Green ""
    Write-Green "  BI MCP        → http://localhost:8101/health"
    Write-Green "  API Hub       → http://localhost:8102/health"
    Write-Green "  Content MCP   → http://localhost:8103/health"
    Write-Green ""
    Write-Green "  Authenticate: X-API-Key: $ApiKey"
    Write-Green ""
    Write-Green "  Stop:    Close the server windows or kill the uvicorn processes"
    Write-Green "  Relaunch: .\launch-servers.ps1"
    Write-Green "════════════════════════════════════════════════"
} else {
    Write-Yellow "════════════════════════════════════════════════"
    Write-Yellow " Deploy finished with warnings — see above"
    Write-Yellow " Troubleshooting guide: docs\QUICKSTART-DEPLOY.md"
    Write-Yellow "════════════════════════════════════════════════"
    exit 1
}
